import { BrandId, ContentItem, PricingTier, BlogPost } from './types';

export const BRANDS = [
  {
    id: BrandId.MILELE,
    name: "SAMN MILELE",
    tagline: "Soulful AI Music & Visuals",
    description: "Experience the future of sound with AI-generated harmonies and music videos.",
    color: "text-purple-400",
    path: "/milele"
  },
  {
    id: BrandId.KIDS,
    name: "SAMONYA KIDS",
    tagline: "Learn, Laugh, Grow",
    description: "Safe, educational, and fun content for the next generation.",
    color: "text-pink-400",
    path: "/kids"
  },
  {
    id: BrandId.SKY,
    name: "SAMN SKY",
    tagline: "The Pulse of Entertainment",
    description: "Top-tier secular music, playlists, and artist spotlights.",
    color: "text-blue-400",
    path: "/sky"
  },
  {
    id: BrandId.TV,
    name: "SAMONYA TV",
    tagline: "News & Digital TV",
    description: "Live updates, breaking news, and digital broadcasting.",
    color: "text-red-500",
    path: "/tv"
  },
  {
    id: BrandId.FILMS,
    name: "SAMONYA FILMS",
    tagline: "Cinematic Innovation",
    description: "Award-winning AI short films and animations.",
    color: "text-gold-500",
    path: "/films"
  }
];

export const CONTENT_DATA: ContentItem[] = [
  // Milele
  { id: 'm1', title: 'Cyber Symphony', thumbnail: 'https://picsum.photos/800/450?random=1', category: BrandId.MILELE, description: 'An AI composed masterpiece.', type: 'song', tags: ['music', 'instrumental'], duration: '3:45' },
  { id: 'm2', title: 'Digital Dreams', thumbnail: 'https://picsum.photos/800/450?random=2', category: BrandId.MILELE, description: 'Music video generated by Veo.', type: 'video', tags: ['music video', 'visuals'], duration: '4:20', premium: true },
  { id: 'm3', title: 'Neon Heartbeat', thumbnail: 'https://picsum.photos/800/450?random=13', category: BrandId.MILELE, description: 'Synthwave rhythms for the soul.', type: 'song', tags: ['music', 'synthwave'], duration: '3:10' },
  { id: 'm4', title: 'Algorithmic Blues', thumbnail: 'https://picsum.photos/800/450?random=14', category: BrandId.MILELE, description: 'Deep blues generated by neural networks.', type: 'song', tags: ['music', 'blues'], duration: '4:05' },
  { id: 'm5', title: 'Virtual Choir', thumbnail: 'https://picsum.photos/800/450?random=15', category: BrandId.MILELE, description: '100 AI voices singing in harmony.', type: 'video', tags: ['music video', 'choir'], duration: '5:00', premium: true },
  { id: 'm6', title: 'Silicon Soul', thumbnail: 'https://picsum.photos/800/450?random=16', category: BrandId.MILELE, description: 'A journey into the machine mind.', type: 'song', tags: ['music', 'ambient'], duration: '6:30' },
  { id: 'm7', title: 'Future Funk', thumbnail: 'https://picsum.photos/800/450?random=17', category: BrandId.MILELE, description: 'Upbeat tracks for coding.', type: 'song', tags: ['music', 'funk'], duration: '2:45' },
  
  // Kids
  { id: 'k1', title: 'The Alphabet Space Journey', thumbnail: 'https://picsum.photos/800/450?random=3', category: BrandId.KIDS, description: 'Learn ABCs in zero gravity!', type: 'video', tags: ['educational', 'animation'], duration: '10:00' },
  { id: 'k2', title: 'Counting with Dinos', thumbnail: 'https://picsum.photos/800/450?random=4', category: BrandId.KIDS, description: '1, 2, 3... Roar!', type: 'video', tags: ['educational', 'animation', 'math'], duration: '5:30' },
  { id: 'k3', title: 'Safari Adventure', thumbnail: 'https://picsum.photos/800/450?random=18', category: BrandId.KIDS, description: 'Meet the animals of the savanna.', type: 'video', tags: ['nature', 'animation'], duration: '12:00' },
  { id: 'k4', title: 'Colors of the Rainbow', thumbnail: 'https://picsum.photos/800/450?random=19', category: BrandId.KIDS, description: 'Sing along and learn colors.', type: 'song', tags: ['music', 'educational'], duration: '3:00' },
  { id: 'k5', title: 'Little Robot Friend', thumbnail: 'https://picsum.photos/800/450?random=20', category: BrandId.KIDS, description: 'A story about friendship.', type: 'video', tags: ['story', 'animation'], duration: '8:45', premium: true },
  { id: 'k6', title: 'Shape Shifters', thumbnail: 'https://picsum.photos/800/450?random=21', category: BrandId.KIDS, description: 'Learning geometry is fun!', type: 'video', tags: ['educational', 'math'], duration: '6:15' },
  { id: 'k7', title: 'Sleepy Time Lullaby', thumbnail: 'https://picsum.photos/800/450?random=22', category: BrandId.KIDS, description: 'Calming music for bedtime.', type: 'song', tags: ['music', 'lullaby'], duration: '30:00' },

  // Sky
  { id: 's1', title: 'Urban Nights Playlist', thumbnail: 'https://picsum.photos/800/450?random=5', category: BrandId.SKY, description: 'Chill vibes for the city.', type: 'song', tags: ['music', 'playlist'], duration: '45:00' },
  { id: 's2', title: 'Pop Culture Weekly', thumbnail: 'https://picsum.photos/800/450?random=6', category: BrandId.SKY, description: 'Recap of the weeks hits.', type: 'video', tags: ['entertainment', 'news'], duration: '15:00' },
  { id: 's3', title: 'Afro-Beats Top 10', thumbnail: 'https://picsum.photos/800/450?random=23', category: BrandId.SKY, description: 'The hottest tracks this month.', type: 'song', tags: ['music', 'chart'], duration: '40:00', premium: true },
  { id: 's4', title: 'Artist Spotlight: J-Maina', thumbnail: 'https://picsum.photos/800/450?random=24', category: BrandId.SKY, description: 'Interview with the rising star.', type: 'video', tags: ['interview', 'documentary'], duration: '20:00' },
  { id: 's5', title: 'Nairobi Drill Mix', thumbnail: 'https://picsum.photos/800/450?random=25', category: BrandId.SKY, description: 'Hard hitting beats.', type: 'song', tags: ['music', 'drill'], duration: '35:00' },

  // TV
  { id: 't1', title: 'Global Tech Report', thumbnail: 'https://picsum.photos/800/450?random=7', category: BrandId.TV, description: 'Latest in AI and Robotics.', type: 'article', tags: ['news', 'tech'], date: '2023-10-24' },
  { id: 't2', title: 'Evening News Live', thumbnail: 'https://picsum.photos/800/450?random=8', category: BrandId.TV, description: 'Breaking stories from around the world.', type: 'video', tags: ['news', 'live'], duration: 'Live', premium: true },
  { id: 't3', title: 'Sports Weekend', thumbnail: 'https://picsum.photos/800/450?random=26', category: BrandId.TV, description: 'Goals, highlights and analysis.', type: 'video', tags: ['sports', 'highlights'], duration: '45:00' },
  { id: 't4', title: 'Business Daily', thumbnail: 'https://picsum.photos/800/450?random=27', category: BrandId.TV, description: 'Market trends and analysis.', type: 'article', tags: ['news', 'business'], date: '2023-10-25' },
  { id: 't5', title: 'Weather Forecast', thumbnail: 'https://picsum.photos/800/450?random=28', category: BrandId.TV, description: 'Weekly weather updates.', type: 'video', tags: ['weather', 'update'], duration: '5:00' },

  // Films
  { id: 'f1', title: 'The Last Android', thumbnail: 'https://picsum.photos/800/450?random=9', category: BrandId.FILMS, description: 'A short film about empathy.', type: 'film', tags: ['sci-fi', 'drama'], duration: '12:00', premium: true },
  { id: 'f2', title: 'Neo-Nairobi 2099', thumbnail: 'https://picsum.photos/800/450?random=10', category: BrandId.FILMS, description: 'Animated sci-fi thriller.', type: 'film', tags: ['animation', 'sci-fi'], duration: '22:00' },
  { id: 'f3', title: 'The Savannah Ghost', thumbnail: 'https://picsum.photos/800/450?random=29', category: BrandId.FILMS, description: 'A mystery set in the wild.', type: 'film', tags: ['mystery', 'thriller'], duration: '18:00' },
  { id: 'f4', title: 'Cyber-Love', thumbnail: 'https://picsum.photos/800/450?random=30', category: BrandId.FILMS, description: 'Romance in the digital age.', type: 'film', tags: ['romance', 'drama'], duration: '15:00' },
  { id: 'f5', title: 'Genesis Code', thumbnail: 'https://picsum.photos/800/450?random=31', category: BrandId.FILMS, description: 'How it all began.', type: 'film', tags: ['documentary', 'sci-fi'], duration: '30:00', premium: true },
  { id: 'f6', title: 'Lost Signal', thumbnail: 'https://picsum.photos/800/450?random=32', category: BrandId.FILMS, description: 'Deep space horror.', type: 'film', tags: ['horror', 'sci-fi'], duration: '14:00' },
  { id: 'f7', title: 'Paper Planes', thumbnail: 'https://picsum.photos/800/450?random=33', category: BrandId.FILMS, description: 'A heartwarming story.', type: 'film', tags: ['animation', 'family'], duration: '08:00' },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'free',
    name: 'Explorer',
    price: '$0',
    features: ['Access to Standard Content', 'Ad-supported Viewing', 'Community Comments']
  },
  {
    id: 'basic',
    name: 'Fan',
    price: '$4.99/mo',
    features: ['Ad-free Experience', 'HD Streaming', 'Exclusive Playlists'],
    recommended: true
  },
  {
    id: 'pro',
    name: 'Super Fan',
    price: '$9.99/mo',
    features: ['4K Downloads', 'Early Access to Films', 'Kids Premium Learning', 'Offline Mode']
  },
  {
    id: 'vip',
    name: 'Universe VIP',
    price: '$19.99/mo',
    features: ['All Pro Features', 'Behind the Scenes', 'Producer Credits', 'Merch Discounts', 'VIP Support']
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'How AI is Reshaping Music Production',
    excerpt: 'Explore the tools and techniques behind Samn Milele.',
    content: 'Full article content here...',
    author: 'Samonya Editor',
    date: 'Oct 25, 2023',
    image: 'https://picsum.photos/800/400?random=11',
    tags: ['AI', 'Music', 'Tech']
  },
  {
    id: 'b2',
    title: 'Top 10 Educational Cartoons for 2024',
    excerpt: 'Curated list for parents and teachers.',
    content: 'Full article content here...',
    author: 'Kids Content Team',
    date: 'Oct 20, 2023',
    image: 'https://picsum.photos/800/400?random=12',
    tags: ['Kids', 'Education']
  }
];