
import { Brand, BrandId, ContentItem } from './types';
import { 
  Music, Baby, Sun, Tv, Clapperboard, Smile, Newspaper, Radio, Lightbulb, Eye, Video, Bot, GraduationCap, Briefcase
} from 'lucide-react';
import React from 'react';

// We map icons in the component rendering phase, but keep keys here
export const BRAND_ICONS: Record<BrandId, React.ElementType> = {
  [BrandId.SAMONYA_AI]: Bot,
  [BrandId.ACADEMY]: GraduationCap,
  [BrandId.DREAM_EYE]: Eye,
  [BrandId.MOTIVATION]: Lightbulb,
  [BrandId.MILELE]: Music,
  [BrandId.KIDS]: Baby,
  [BrandId.SKY]: Sun,
  [BrandId.TV]: Tv,
  [BrandId.FILMS]: Clapperboard,
  [BrandId.COMEDY]: Smile,
  [BrandId.BLOG]: Newspaper,
  [BrandId.LIVE]: Radio,
  [BrandId.BUSINESS_MATRIX]: Briefcase
};

// Reordered list: Complex tasks first (AI, Academy, Dream, Motivation)
export const BRANDS: Brand[] = [
  {
    id: BrandId.SAMONYA_AI,
    name: "SAMONYA AI",
    tagline: "Pure Intelligence. Beyond Boundaries.",
    description: "The next evolution of generative intelligence. Capable of advanced reasoning, complex coding, creative writing, and deep analysis.",
    color: "text-cyan-400",
    gradient: "from-cyan-500 via-blue-500 to-indigo-500",
    icon: "Bot",
    route: "/samonya-ai",
    themeColor: "bg-slate-950",
    textColor: "text-cyan-50"
  },
  {
    id: BrandId.BUSINESS_MATRIX,
    name: "SAMONYA BUSINESS MATRIX™",
    tagline: "Build. Grow. Scale.",
    description: "The ultimate AI-powered ecosystem for entrepreneurs. Generate business plans, pitch decks, legal docs, and financial forecasts instantly.",
    color: "text-[#00F5D4]",
    gradient: "from-[#0D1B2A] to-[#1B263B]",
    icon: "Briefcase",
    route: "/business-matrix",
    themeColor: "bg-[#0D1B2A]",
    textColor: "text-[#E0E6ED]"
  },
  {
    id: BrandId.ACADEMY,
    name: "SAMONYA ACADEMY",
    tagline: "Research. Learn. Master.",
    description: "An advanced AI research ecosystem. Features deep research, book condensation, brand monitoring, and interactive study tools.",
    color: "text-amber-400",
    gradient: "from-slate-800 to-slate-950",
    icon: "GraduationCap",
    route: "/academy",
    themeColor: "bg-gray-900",
    textColor: "text-white"
  },
  {
    id: BrandId.DREAM_EYE,
    name: "SAMONYA DREAM EYE",
    tagline: "The Eye That Sees Beyond",
    description: "AI-powered dream interpretation and cinematic dream visualization. Decode your subconscious.",
    color: "text-fuchsia-400",
    gradient: "from-fuchsia-600 via-purple-600 to-cyan-500",
    icon: "Eye",
    route: "/dream-eye",
    themeColor: "bg-slate-950",
    textColor: "text-white"
  },
  {
    id: BrandId.MOTIVATION,
    name: "SAMONYA MOTIVATION",
    tagline: "Ignite Your Inner Fire",
    description: "Generate powerful, personalized quotes to inspire your day instantly with AI.",
    color: "text-amber-400",
    gradient: "from-amber-400 to-orange-500",
    icon: "Lightbulb",
    route: "/motivation",
    themeColor: "bg-slate-900",
    textColor: "text-white"
  },
  {
    id: BrandId.MILELE,
    name: "SAMN MILELE",
    tagline: "Spiritual & Gospel",
    description: "Deep dive into religious truths, gospel music, and spiritual articles exposing hidden mysteries.",
    color: "text-slate-100",
    gradient: "from-slate-100 to-slate-300",
    icon: "Music",
    route: "/milele",
    themeColor: "bg-slate-50",
    textColor: "text-slate-900"
  },
  {
    id: BrandId.KIDS,
    name: "SAMONYA KIDS",
    tagline: "Fun Learning & Stories",
    description: "A safe world of educational fun, animated stories, and learning adventures for children.",
    color: "text-green-500", 
    gradient: "from-green-400 to-emerald-500",
    icon: "Baby",
    route: "/kids",
    themeColor: "bg-green-500",
    textColor: "text-white"
  },
  {
    id: BrandId.SKY,
    name: "SAMN SKY",
    tagline: "Trending, Celebs & Comedy",
    description: "The home of celebrity lifestyle, trending memes, funny jokes, and secular arts.",
    color: "text-pink-400",
    gradient: "from-pink-400 to-rose-500",
    icon: "Sun",
    route: "/sky",
    themeColor: "bg-pink-500",
    textColor: "text-white"
  },
  {
    id: BrandId.TV,
    name: "SAMONYA TV",
    tagline: "News, History & Truth",
    description: "Documentaries, global warming, political history, sports, and AI revolutions.",
    color: "text-blue-500",
    gradient: "from-blue-600 to-cyan-600",
    icon: "Tv",
    route: "/tv",
    themeColor: "bg-blue-700",
    textColor: "text-white"
  },
  {
    id: BrandId.FILMS,
    name: "SAMONYA FILMS",
    tagline: "AI Movies & Stories",
    description: "Romantic, Action, and Thriller movie stories generated by AI.",
    color: "text-slate-200",
    gradient: "from-slate-700 to-black",
    icon: "Clapperboard",
    route: "/films",
    themeColor: "bg-slate-900",
    textColor: "text-white"
  },
  {
    id: BrandId.COMEDY,
    name: "SAMONYA COMEDY",
    tagline: "Laugh Out Loud",
    description: "Your daily dose of laughter with hilarious skits and shorts.",
    color: "text-orange-500", 
    gradient: "from-orange-400 to-red-500",
    icon: "Smile",
    route: "/comedy",
    themeColor: "bg-orange-500",
    textColor: "text-white"
  },
  {
    id: BrandId.LIVE,
    name: "SAMONYA LIVE",
    tagline: "Live Events & Streaming",
    description: "Watch live events and broadcasts from the Samonya Universe.",
    color: "text-red-600",
    gradient: "from-red-600 to-red-900",
    icon: "Radio",
    route: "/live",
    themeColor: "bg-red-900",
    textColor: "text-white"
  }
];

// --- CONTENT FACTORY ---

// Helper to generate consistent pseudo-random numbers
const seededRandom = (seed: number) => {
    const x = Math.sin(seed++) * 10000;
    return x - Math.floor(x);
};

const generateArticles = (brandId: BrandId, count: number, startId: number): ContentItem[] => {
    const items: ContentItem[] = [];
    
    const subjects: Record<string, string[]> = {
        [BrandId.MILELE]: ['The Lost Gospel', 'Hidden Angels', 'Faith in Crisis', 'The Silent Prayer', 'Divine Intervention', 'Ancient Scriptures Decoded', 'The Power of Fasting', 'Miracles Today'],
        [BrandId.FILMS]: ['Forbidden Love (Romance)', 'Cyber Agent 009 (Action)', 'The Last Stand (Thriller)', 'Love in Paris (Romance)', 'Robot Wars (Action)', 'The Ghost of Tomorrow (Horror)', 'Speed Chase (Action/Romance)'],
        [BrandId.KIDS]: ['Learning Colors', 'The Brave Little Lion', 'Counting Stars', 'ABC Adventure', 'Why is the Sky Blue?', 'The Friendly Dragon', 'Magic Numbers', 'Space Explorer'],
        [BrandId.TV]: ['The AI Revolution', 'Climate Change Reality', 'Political Secrets Exposed', 'History of Kings', 'Global Sports Recap', 'Tech Future 2050', 'The Great Depression Truth', 'Nature\'s Fury'],
        [BrandId.SKY]: ['Top 10 Celeb Secrets', 'Meme of the Year', 'Viral TikTok Trends', 'Comedy Gold', 'Rapper Lifestyle', 'Hollywood Uncut', 'Fashion Fails', 'Best Jokes 2024'],
        [BrandId.MOTIVATION]: ['Inspire'], // Handled separately
        [BrandId.ACADEMY]: ['Research'], // Handled separately
        [BrandId.DREAM_EYE]: ['Lucid Dreaming Guide', 'Nightmares Explained', 'Astral Projection'],
        [BrandId.SAMONYA_AI]: ['AI Consciousness', 'Future of Robotics', 'Human-AI Friendship'],
        [BrandId.COMEDY]: ['Funny Prank', 'Office Fails'],
        [BrandId.BLOG]: ['Blog Post'],
        [BrandId.LIVE]: ['Live Stream'],
        [BrandId.BUSINESS_MATRIX]: ['Startup Guide', 'Market Trends 2025', 'Crypto Future', 'Leadership 101']
    };

    const tagsList = ['Trending', 'Viral', 'New', 'Must Watch', 'Exclusive', 'Hidden Truth', 'AI Generated'];

    for (let i = 0; i < count; i++) {
        const seed = startId + i;
        const brandSubjects = subjects[brandId] || ['General'];
        const subject = brandSubjects[Math.floor(seededRandom(seed) * brandSubjects.length)];
        const title = `${subject}: Part ${i + 1}`;
        
        items.push({
            id: `gen-${brandId}-${i}`,
            title: title,
            description: `A 5000+ word deep dive into ${subject}. Generated by AI, this article exposes the hidden truths and realities of the topic.`,
            thumbnail: `https://picsum.photos/seed/${brandId}${i}/800/450`,
            brandId: brandId,
            type: 'article',
            isPremium: i % 5 === 0, // Every 5th item is premium
            date: new Date(Date.now() - Math.floor(seededRandom(seed) * 10000000000)).toISOString(),
            tags: [tagsList[Math.floor(seededRandom(seed) * tagsList.length)], 'AI', 'Deep Dive'],
            views: Math.floor(seededRandom(seed) * 50000) + 500,
            interactions: { 
                likes: Math.floor(seededRandom(seed) * 2000), 
                loves: Math.floor(seededRandom(seed) * 500), 
                dislikes: Math.floor(seededRandom(seed) * 50), 
                comments: Math.floor(seededRandom(seed) * 100) 
            },
            commentList: []
        });
    }
    return items;
};

// Generate 50 items for each main brand (Excluding motivation/dreams to keep it clear for the generator)
const mileleContent = generateArticles(BrandId.MILELE, 50, 1000);
const filmsContent = generateArticles(BrandId.FILMS, 50, 2000);
const kidsContent = generateArticles(BrandId.KIDS, 50, 3000);
const tvContent = generateArticles(BrandId.TV, 50, 4000);
const skyContent = generateArticles(BrandId.SKY, 50, 5000);

export const INITIAL_CONTENT: ContentItem[] = [
  ...mileleContent,
  ...filmsContent,
  ...kidsContent,
  ...tvContent,
  ...skyContent,
  {
    id: '1',
    title: 'Celestial Harmonies - Angelic Symphony',
    description: 'A divine AI composed masterpiece featuring angelic choirs and uplifting spiritual melodies.',
    thumbnail: 'https://picsum.photos/800/450?random=1',
    brandId: BrandId.MILELE,
    type: 'music',
    isPremium: false,
    date: '2023-10-15',
    tags: ['AI', 'Music', 'Gospel', 'Spiritual'],
    views: 12500,
    interactions: { likes: 120, loves: 45, dislikes: 2, comments: 2 },
    commentList: []
  },
  {
      id: 'dream-intro',
      title: 'The Science of REM Sleep',
      description: 'Understanding the state where dreams happen.',
      thumbnail: 'https://picsum.photos/800/450?random=99',
      brandId: BrandId.DREAM_EYE,
      type: 'article',
      isPremium: false,
      date: '2023-11-01',
      tags: ['Science', 'Sleep', 'Dreams'],
      views: 3400,
      interactions: { likes: 100, loves: 20, dislikes: 0, comments: 5 },
      commentList: []
  }
];

export const PLANS = [
  {
    id: 'free',
    name: 'Explorer',
    price: 'Free',
    features: ['Access to free content', 'Standard quality', 'Community access'],
    isPremium: false
  },
  {
    id: 'monthly',
    name: 'Universe Plus',
    price: '$4.99/mo',
    features: ['Ad-free experience', 'Exclusive Originals', 'High-Res Audio', 'Dream Analysis (Basic)'],
    isPremium: true
  },
  {
    id: 'yearly',
    name: 'Galactic Pass',
    price: '$49.99/yr',
    features: ['All Monthly features', 'Offline Downloads', 'VIP Live Events', 'Unlimited Dream Visuals'],
    isPremium: true
  },
  {
    id: 'family',
    name: 'Cosmic Family',
    price: '$14.99/mo',
    features: ['Up to 4 accounts', 'Parental Controls', 'Kids Mode'],
    isPremium: true
  }
];
